---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jow.hou.
--- DateTime: 2019/4/24 8:12
---this is lua kata main entry file.

require("core.class")
print("Hello kata!")
print("This is my first kata, just do it.")
--local  test = class("test",{2,3,4})
--test:new()
--.\core\class.lua:78: attempt to call method 'ctor' (a nil value)

