---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jow.hou.
--- DateTime: 2019/4/24 17:26
---this file is the practice of cocos class

local function class(className, super)
    local superType = type(super)
    local cls
    if superType ~= "table" or superType ~= "function" then
        super = nil
        superType = nil
    end

    if superType == "function" or (super and super.__ctype == 1) then
        cls = {}
        if superType == "table" then
            cls.__create = super.__create
            cls.super = super
            for k, v in pairs(super) do
                cls[k] = v
            end
        else
            cls.__create = super
            cla.ctor = function() end -- forget
        end
        cls.__ctype = 1
        cls.__cname = className
        function cls.new(...)
            local instance = cls.__create(...)
            for k, v in pairs(cls) do
                instance[k] = v
            end
            instance.class = cls
            instance:ctor(...)
            return instance
        end
    else
        if super then
            cls = {}
            cls.super = super
            setmetatable(cls,{__index = super})
        else
            cls.ctor = {function () end}
        end
        cls.__cname = className
        cls.__ctype = 2
        cls.__index = cls
        function cls.new(...)
            local instance = setmetatable({},cls)
            instance.class = cls
            instance:ctor(...)
            return instance
        end
    end
    return cls
end