---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jow.hou.
--- DateTime: 2019/4/24 15:44
--- this file is kata for class
local function class(className, super)
    local superType = type(super)
    local cls
    if superType ~= "function" and superType ~= "table" then
        superType = nil
        super = nil
    end

    if superType == "function" or (super and super.__ctype == 1) then
        cls = {} -- forget
        if superType == "table" then
            for k, v in pairs(super) do
                cls[k] = v
            end
            cls.__create = super.__create
            cls.super = super
        else
            cls.__create = super
            cls.ctor = function() end --forget
        end
        cls.__ctype = 1
        cls.__cname = className
        function cls.new(...)
            local instance = cls.__create(...)
            for k, v in pairs(cls) do
                instance[k] = v
            end
            instance.class = cls
            instance:ctor(...)
            return instance
        end
    else
        if super then
            -- forget
            cls = {}
            setmetatable(cls, { __index = super })
            cls.super = super
        else
            cls = { ctor = function()
            end }
        end
        cls.__ctype = 2
        cls.__cname = className
        cls.__index = cls --forget
        function cls.new(...)
            local instance = setmetatable({}, cls)
            instance.class = cls
            instance:ctor(...)
            return instance
        end
    end
    return cls
end

