---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jow.hou.
--- DateTime: 2019/4/25 9:03
---this file is for class kata three
---
local function class(className, super)
    local superType = type(super)
    local cls
    if superType ~= "function" and supertype ~= "table" then
        super = nil
        superType = nil
    end
    if superType == "function"or (super and super.__ctype == 1) then
        cls = {}
        if superType == "table" then
            for k, v in pairs(super) do
                cls[k] = v
            end
            cls.super = super
        else
            cls.__create = super
            cls.ctor = function() end
        end
        cls.__cname = className
        cls.__ctype = 1
        local __create = cls.__create
        function cls.new(...)
            local instance = __create(...)
            for k, v in pairs(cls) do
                instance[k] = v
            end
            instance.class = cls
            instance:ctor(...)
            return instance
        end
    else
        if super then
            cls = {}
            cls.super = super
            setmetatable(cls,{__index = super})
        else
            cls.ctor = {function () end}
        end
        cls.__ctype = 2
        cls.__cname = className
        cls.__index = cls  --这样设置当自己作为元表的时候可以被索引到  也可以在setmetatable的时候{{},__index = cls}，查找顺序 自己表中，元表是否存在__index键值，存在就可以去元表中索引数据
        function cls.new(...)
            local instance = setmetatable({{},cls})
            instance.class = cls
            instance:ctor(...)
            return instance
        end
    end
    return cls
end